name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "17 21 * * *"

permissions:
  contents: write

concurrency:
  group: leetcode-sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Synchroniser les solutions LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          filter-duplicate-secs: "86400"
          verbose: "true"
          commit-header: "[LeetCode Sync]"
